ApartmentExpensesSystem/ApartmentExpensesSystem/Controllers/HomeController.cs
using ApartmentExpensesSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace ApartmentExpensesSystem.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";

            return View();
        }
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginModel user)
        {
            LoginContext registrationContext = new LoginContext();
            if (registrationContext.findUser(user.UserName, user.Password))
            {
                FormsAuthentication.SetAuthCookie(user.UserName, false);
                return RedirectToAction("Index", "ApartmentResidents");
            }
            else
            {
                TempData["msg"] = "Incorrect User/Password";
            }
            return View();
        }

        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            return View("Login");
        }

    }
}

ApartmentExpensesSystem/ApartmentExpensesSystem/Controllers/RegistrationModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ApartmentExpensesSystem.Models;

namespace ApartmentExpensesSystem.Controllers
{
    public class RegistrationModelsController : Controller
    {
        private RegistrationContext db = new RegistrationContext();

        // GET: RegistrationModels
        public ActionResult Index()
        {
            return View(db.RegistrationModels.ToList());
        }

        // GET: RegistrationModels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RegistrationModel registrationModel = db.RegistrationModels.Find(id);
            if (registrationModel == null)
            {
                return HttpNotFound();
            }
            return View(registrationModel);
        }

        // GET: RegistrationModels/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RegistrationModels/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,UserName,Password,Email,FullName")] RegistrationModel registrationModel)
        {
            if (ModelState.IsValid)
            {
                db.RegistrationModels.Add(registrationModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(registrationModel);
        }

        // GET: RegistrationModels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RegistrationModel registrationModel = db.RegistrationModels.Find(id);
            if (registrationModel == null)
            {
                return HttpNotFound();
            }
            return View(registrationModel);
        }

        // POST: RegistrationModels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,UserName,Password,Email,FullName")] RegistrationModel registrationModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(registrationModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(registrationModel);
        }

        // GET: RegistrationModels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RegistrationModel registrationModel = db.RegistrationModels.Find(id);
            if (registrationModel == null)
            {
                return HttpNotFound();
            }
            return View(registrationModel);
        }

        // POST: RegistrationModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RegistrationModel registrationModel = db.RegistrationModels.Find(id);
            db.RegistrationModels.Remove(registrationModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ApartmentExpensesSystem/ApartmentExpensesSystem/Views/Home/Index.cshtml
<h5>This is a basic web page about APARTMENT EXPENSES APPLICATION</h5>

ApartmentExpensesSystem/ApartmentExpensesSystem/Views/Home/Login.cshtml
@model ApartmentExpensesSystem.Models.LoginModel

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>
@{
    if (TempData["msg"] != null)
    {
        <label style="color:red">@TempData["msg"]</label>
    }
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="col-md-10">
            <label id="wrongUser" style="color:red"></label>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("New User", "Create", "RegistrationModels")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}